title: Buildpack CI
description: Heroku-style CI on GitHub
sitename: Buildpack CI
baseurl: ''
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
logo_url: images/logo.png
